parameters:
- name: Clouds
  type: string
  default: 'AzureCloud,AzureCloud_Preview'
- name: Platforms
  type: object
  default: []
- name: AdditionalParameters
  type: object
  default: []
- name: Location
  type: string
- name: CloudConfig
  type: object
  default:
    AzureCloud:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
      ArmTemplateParameters: >-
        @{ keyVaultDomainSuffix = '.vault.azure.net';
           storageEndpointSuffix = 'core.windows.net';
           endpointSuffix = '.cognitiveservices.azure.com';
           azureAuthorityHost = 'https://login.microsoftonline.com/';
           keyVaultEndpointSuffix = '.vault.azure.net' }
      EnvVars:
        SERVICE_MANAGEMENT_URL: https://management.core.windows.net/
        STORAGE_ENDPOINT_SUFFIX: core.windows.net
        RESOURCE_MANAGER_URL: https://management.azure.com/
        SEARCH_ENDPOINT_SUFFIX: search.windows.net
        COSMOS_TABLES_ENDPOINT_SUFFIX: cosmos.azure.com
    AzureCloud_Preview:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)
    AzureCloud_Canary:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)
      Location: 'eastus2euap'
    AzureUsGovCloud:
      SubscriptionConfiguration: $(sub-config-gov-test-resources)
      ArmTemplateParameters: >-
        @{ keyVaultDomainSuffix = '.vault.usgovcloudapi.net';
           storageEndpointSuffix = 'core.usgovcloudapi.net';
           endpointSuffix = '.cognitiveservices.azure.us';
           azureAuthorityHost = 'https://login.microsoftonline.us/';
           keyVaultEndpointSuffix = '.vault.usgovcloudapi.net';
           enableStorageVersioning = $false }
      EnvVars:
        AZURE_AUTHORITY_HOST: https://login.microsoftonline.us
        RESOURCE_MANAGER_URL: https://management.usgovcloudapi.net/
        STORAGE_ENDPOINT_SUFFIX: core.usgovcloudapi.net
        SERVICE_MANAGEMENT_URL: https://management.core.usgovcloudapi.net/
        SEARCH_ENDPOINT_SUFFIX: search.azure.us
        COSMOS_TABLES_ENDPOINT_SUFFIX: cosmos.azure.us
    AzureChinaCloud:
      SubscriptionConfiguration: $(sub-config-cn-test-resources)
      ArmTemplateParameters: >-
        @{ keyVaultDomainSuffix = '.vault.azure.cn';
           storageEndpointSuffix = 'core.chinacloudapi.cn';
           azureAuthorityHost = 'https://login.chinacloudapi.cn/';
           keyVaultEndpointSuffix = '.vault.azure.cn';
           keyVaultSku = 'standard';
           enableStorageVersioning = $false;
           endpointSuffix = '.cognitiveservices.azure.cn';
           textAnalyticsSku = 'S' }
      EnvVars:
        AZURE_AUTHORITY_HOST: https://login.chinacloudapi.cn
        SERVICE_MANAGEMENT_URL: https://management.core.chinacloudapi.cn/
        RESOURCE_MANAGER_URL: https://management.chinacloudapi.cn
        STORAGE_ENDPOINT_SUFFIX: core.chinacloudapi.cn
        SEARCH_ENDPOINT_SUFFIX: search.azure.cn
        COSMOS_TABLES_ENDPOINT_SUFFIX: cosmos.azure.cn


stages:
  - ${{ each cloud in parameters.CloudConfig }}:
    - stage: ${{ cloud.key }}
      # By default enable all cloud stages for manual runs, so as to defer to the stage picker in the UI
      condition: or(eq(variables['Build.Reason'], 'Manual'), contains('${{ parameters.Clouds }}', '${{ cloud.key }}'))
      dependsOn: []
      jobs:
      - template: ../jobs/archetype-sdk-tests-platforms.yml
        parameters:
          AdditionalParameters: ${{ parameters.AdditionalParameters }}
          Platforms:
            ${{ each platform in parameters.Platforms }}:
              # Only run this platform against the clouds specified in its parameter config
              ${{ if contains(platform.value.RunInClouds, cloud.key) }}:
                ${{ platform.key }}: ${{ platform.value }}
          CloudConfig:
            DisplayName: ${{ cloud.key }}
            # Default to AzureCloud configuration values when not set in the provided cloud config
            SubscriptionConfiguration: ${{ coalesce(cloud.value.SubscriptionConfiguration, parameters.CloudConfig.AzureCloud.SubscriptionConfiguration) }}
            ArmTemplateParameters: ${{ coalesce(cloud.value.ArmTemplateParameters, parameters.CloudConfig.AzureCloud.ArmTemplateParameters) }}
            EnvVars:
              ${{ if cloud.value.EnvVars.AZURE_AUTHORITY_HOST }}:
                AZURE_AUTHORITY_HOST: ${{ cloud.value.EnvVars.AZURE_AUTHORITY_HOST }}
              RESOURCE_MANAGER_URL: ${{ coalesce(cloud.value.EnvVars.RESOURCE_MANAGER_URL, parameters.CloudConfig.AzureCloud.EnvVars.RESOURCE_MANAGER_URL) }}
              STORAGE_ENDPOINT_SUFFIX: ${{ coalesce(cloud.value.EnvVars.STORAGE_ENDPOINT_SUFFIX, parameters.CloudConfig.AzureCloud.EnvVars.STORAGE_ENDPOINT_SUFFIX) }}
              SERVICE_MANAGEMENT_URL: ${{ coalesce(cloud.value.EnvVars.SERVICE_MANAGEMENT_URL, parameters.CloudConfig.AzureCloud.EnvVars.SERVICE_MANAGEMENT_URL) }}
              SEARCH_ENDPOINT_SUFFIX: ${{ coalesce(cloud.value.EnvVars.SEARCH_ENDPOINT_SUFFIX, parameters.CloudConfig.AzureCloud.EnvVars.SEARCH_ENDPOINT_SUFFIX) }}
              COSMOS_TABLES_ENDPOINT_SUFFIX: ${{ coalesce(cloud.value.EnvVars.COSMOS_TABLES_ENDPOINT_SUFFIX, parameters.CloudConfig.AzureCloud.EnvVars.COSMOS_TABLES_ENDPOINT_SUFFIX) }}
            # Inject location override, if provided, otherwise default to a local override or the ARM default
            Location: ${{ coalesce(parameters.Location, cloud.value.Location, '') }}
